### ISSUE TITLE
Shopify GDPR Webhook Integration

### ISSUE THREAD

**Issue by akeans-mgs** [Shopify/quilt#2215] opened 2022-03-14 05:33 UTC
Our app was rejected by Shopify's automated submission test immediately after submission with the same reason of

> App must verify the authenticity of the request from Shopify.
> Expected HTTP 401 (Unauthorized), but got HTTP 405 from https://8235cf20c428.ngrok.io/webhook/gdpr/shop_redact. Your app's HTTPS webhook endpoints must validate the HMAC digest of each request, and return an HTTP 401 (Unauthorized) response when rejecting a request that has an invalid digest.

Error I received

```
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined in
at Hmac.update (internal/crypto/hash.js:84:11)
at receiveWebhookMiddleware( \node_modules@shopify\koa-shopify-webhooks\build\cjs\receive.js:32:63 )
at dispatch( \node_modules@shopify\koa-shopify-webhooks\node_modules\koa-compose\index.js:42:32 )
at bodyParser \node_modules\koa-bodyparser\index.js:95:11)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at \node_modules\koa-mount\index.js:58:5
```

You can check the code here.
https://github.com/akeans-mgs/mgs_testing

**Comment by TrevPennington** [comment] 2022-04-12 20:49
+1

**Comment by BPScott** [comment] 2022-04-12 20:57
Duplicate of #2233 2177

**Closed by BPScott** 2022-04-12 20:57 UTC
Labels: Type: Bug 🐛
